# Generated by Django 6.0.3 on 2026-03-23 12:17

import api_v1.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.CharField(default=api_v1.models.message_id_default, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=16)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.CharField(default=api_v1.models.session_id_default, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('owner_type', models.CharField(choices=[('anonymous', 'Anonymous'), ('student', 'Student')], max_length=20)),
                ('anonymous_session_key', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api_v1.chatmessage')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api_v1.chatsession'),
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation_id', models.CharField(max_length=64)),
                ('source_id', models.CharField(db_index=True, max_length=64)),
                ('chunk_id', models.CharField(max_length=64)),
                ('snippet', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=1000)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('doc_metadata', models.JSONField(blank=True, default=dict)),
                ('score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='api_v1.chatmessage')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.CharField(default=api_v1.models.feedback_id_default, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('rating', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], max_length=8)),
                ('reason', models.CharField(blank=True, choices=[('incorrect', 'Incorrect'), ('incomplete', 'Incomplete'), ('unsafe', 'Unsafe'), ('other', 'Other')], max_length=16, null=True)),
                ('comment', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='api_v1.chatmessage')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='api_v1.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='IngestJob',
            fields=[
                ('id', models.CharField(default=api_v1.models.ingest_id_default, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('status', models.CharField(default='accepted', max_length=16)),
                ('idempotency_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('accepted_count', models.IntegerField(default=0)),
                ('submitted_by_role', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingest_jobs', to=settings.AUTH_USER_MODEL)),
                ('submitted_by_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingest_jobs', to='api_v1.servicetoken')),
            ],
        ),
        migrations.CreateModel(
            name='SourceChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(db_index=True, max_length=64)),
                ('chunk_id', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=1000)),
                ('snippet', models.TextField()),
                ('page', models.IntegerField(blank=True, null=True)),
                ('doc_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source_id', 'chunk_id'), name='uniq_source_chunk')],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['owner_type', 'owner_user'], name='api_v1_chat_owner_t_0f4763_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['owner_type', 'anonymous_session_key'], name='api_v1_chat_owner_t_5bddd9_idx'),
        ),
        migrations.AddConstraint(
            model_name='citation',
            constraint=models.UniqueConstraint(fields=('message', 'citation_id'), name='uniq_message_citation_id'),
        ),
    ]
